export enum UserRole {
  CONSUMER = 'CONSUMER',
  VENDOR = 'VENDOR',
  MERCHANT = 'MERCHANT',
  DELIVERY_AGENT = 'DELIVERY_AGENT',
  ADMIN = 'ADMIN',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPERATIONS_ADMIN = 'OPERATIONS_ADMIN',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  COMPLIANCE_ADMIN = 'COMPLIANCE_ADMIN',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  CUSTOMER_SUPPORT_MANAGER = 'CUSTOMER_SUPPORT_MANAGER',
}

export enum KYCStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RESUBMISSION_REQUIRED = 'RESUBMISSION_REQUIRED',
}

export enum KYCLevel {
  LEVEL_0 = 0,
  LEVEL_1 = 1,
  LEVEL_2 = 2,
  LEVEL_3 = 3,
}

export enum TransferStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum WalletType {
  NGN = 'NGN',
  USD = 'USD',
  CRYPTO = 'CRYPTO',
}

export enum TransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum AIIntent {
  DEPOSIT = 'DEPOSIT_INTENT',
  WITHDRAW = 'WITHDRAW_INTENT',
  TRANSFER = 'TRANSFER_INTENT',
  BALANCE = 'BALANCE_INTENT',
  BUY_PRODUCT = 'BUY_PRODUCT_INTENT',
  SELL_PRODUCT = 'SELL_PRODUCT_INTENT',
  CARD = 'CARD_INTENT',
  SWAP = 'SWAP_INTENT',
  BUSINESS = 'BUSINESS_INTENT',
  SUPPORT = 'SUPPORT_INTENT',
  ORDER = 'ORDER_INTENT',
  FALLBACK = 'FALLBACK_INTENT',
}

export enum NotificationChannel {
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}